# Generated by Django 3.2.7 on 2021-09-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_to_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
        migrations.RunSQL("""
        INSERT INTO store_collection(title)
        VALUES('collection1')
        """, """
        DELETE FROM store_collection WHERE title='collection1'
        """)
    ]
