# Generated by Django 3.2.7 on 2021-09-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zipcode'),
    ]

    operations = [
    ]
